/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.simulador.views;

import autonoma.simulador.models.Escritor;
import autonoma.simulador.models.EscritorArchivoTextoPlano;
import autonoma.simulador.models.Simulador;
import autonoma.simulador.models.Vehiculo;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * @author Camila Prada
 * @version 1.0.0
 * @since 2025-04-10
 */
public class VentanaCargarConfi extends JFrame{
    private Vehiculo vehiculo;
    /**
     * Creates new form VentanaCargarConfi
     */
    public VentanaCargarConfi(Vehiculo vehiculo) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        try{
            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/simulador/images/CarroFondo.png")).getImage());
        }catch(Exception e){
            System.out.println("imagen no encontrada");
        }
        this.vehiculo = vehiculo;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCargarConfi = new javax.swing.JPanel();
        btnConfi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxLlantas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboMotor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        btnCargarConfi.setBackground(new java.awt.Color(102, 102, 102));

        btnConfi.setBackground(new java.awt.Color(0, 0, 0));
        btnConfi.setForeground(new java.awt.Color(255, 255, 255));
        btnConfi.setText("Cargar Configuración");
        btnConfi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfiMouseClicked(evt);
            }
        });
        btnConfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simulador/images/fondoConfig.gif"))); // NOI18N

        jComboBoxLlantas.setBackground(new java.awt.Color(0, 0, 0));
        jComboBoxLlantas.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxLlantas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LLantas Buenas", "Llantas Bonitas", "Llantas Baratas" }));
        jComboBoxLlantas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jComboBoxLlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLlantasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo de Llantas");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de motor");

        jComboMotor.setBackground(new java.awt.Color(0, 0, 0));
        jComboMotor.setForeground(new java.awt.Color(255, 255, 255));
        jComboMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1000 cc\t", "2000 cc", "3000 cc\t" }));

        javax.swing.GroupLayout btnCargarConfiLayout = new javax.swing.GroupLayout(btnCargarConfi);
        btnCargarConfi.setLayout(btnCargarConfiLayout);
        btnCargarConfiLayout.setHorizontalGroup(
            btnCargarConfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCargarConfiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnCargarConfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCargarConfiLayout.createSequentialGroup()
                        .addGroup(btnCargarConfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCargarConfiLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCargarConfiLayout.createSequentialGroup()
                        .addComponent(jComboBoxLlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnCargarConfiLayout.setVerticalGroup(
            btnCargarConfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCargarConfiLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnCargarConfiLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxLlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCargarConfi, javax.swing.GroupLayout.PREFERRED_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCargarConfi, javax.swing.GroupLayout.PREFERRED_SIZE, 316, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiActionPerformed
        Escritor escritorArchivo = new EscritorArchivoTextoPlano("config.txt");
        String tipoMotor = (String)this.jComboMotor.getSelectedItem();
        String tipoLlanta = (String)this.jComboBoxLlantas.getSelectedItem();
        
        StringBuilder sb = new StringBuilder();
        sb.append("Llantas ").append(tipoLlanta);
        
        StringBuilder sbMotor = new StringBuilder();
        sbMotor.append("Motor ").append(tipoMotor);
        ArrayList<String> textoArchivo = new ArrayList();
        textoArchivo.add(sb.toString());
        textoArchivo.add(sbMotor.toString());
        try{
            escritorArchivo.escribir(textoArchivo);
            VentanaInicial ventana = new VentanaInicial();
            ventana.setVisible(true);
            this.dispose();
        }catch (IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        


    }//GEN-LAST:event_btnConfiActionPerformed

    private void btnConfiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiMouseClicked
        
    }//GEN-LAST:event_btnConfiMouseClicked

    private void jComboBoxLlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLlantasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLlantasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCargarConfi;
    private javax.swing.JButton btnConfi;
    private javax.swing.JComboBox<String> jComboBoxLlantas;
    private javax.swing.JComboBox<String> jComboMotor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
