/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package autonoma.simulador.views;

import autonoma.simulador.models.Vehiculo;
import javax.swing.ImageIcon;

/**
 *
 * @author marti
 */
public class VentanaPrincipal2 extends javax.swing.JDialog {
    private VentanaPrincipal ventana;
    private Vehiculo vehiculo;
    /** Creates new form VentanaPrincipal2 */
    public VentanaPrincipal2(java.awt.Frame parent, boolean modal,Vehiculo vehiculo,VentanaPrincipal ventana) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        try{
           this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/simulador/images/coche.png")).getImage());
        }catch(Exception e){
            
        }
        this.vehiculo=vehiculo;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simulador/views/fotoManubrio.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 530, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
