/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.simulador.views;

import autonoma.simulador.exception.ArchivoExistenteException;
import autonoma.simulador.models.ArchivoConfiguracion;
import autonoma.simulador.models.Lector;
import autonoma.simulador.models.LectorArchivoTextoPlano;
import autonoma.simulador.models.Vehiculo;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Kamii
 */
public class VentanaCargarConfi extends javax.swing.JDialog {
    private Vehiculo vehiculo;
    /**
     * Creates new form VentanaCargarConfi
     */
    public VentanaCargarConfi(java.awt.Frame parent, boolean modal, Vehiculo vehiculo) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        try{
            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/simulador/images/CarroFondo.png")).getImage());
        }catch(Exception e){
            System.out.println("imagen no encontrada");
        }
        this.vehiculo = vehiculo;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCargarConfi = new javax.swing.JPanel();
        btnConfi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simulador/images/fondoConfig.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        btnCargarConfi.setBackground(new java.awt.Color(0, 0, 0));

        btnConfi.setBackground(new java.awt.Color(0, 0, 0));
        btnConfi.setForeground(new java.awt.Color(255, 255, 255));
        btnConfi.setText("Cargar Configuración");
        btnConfi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfiMouseClicked(evt);
            }
        });
        btnConfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnCargarConfiLayout = new javax.swing.GroupLayout(btnCargarConfi);
        btnCargarConfi.setLayout(btnCargarConfiLayout);
        btnCargarConfiLayout.setHorizontalGroup(
            btnCargarConfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCargarConfiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfi)
                .addGap(218, 218, 218))
        );
        btnCargarConfiLayout.setVerticalGroup(
            btnCargarConfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCargarConfiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConfi)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCargarConfi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCargarConfi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    int resultado = fileChooser.showOpenDialog(this);

    if (resultado == JFileChooser.APPROVE_OPTION) {
        File archivo = fileChooser.getSelectedFile();

        Lector lector = new LectorArchivoTextoPlano();
        ArchivoConfiguracion config = new ArchivoConfiguracion(lector);
        this.vehiculo = vehiculo;

        try {
            if (config.archivoExiste(archivo.getAbsolutePath())) {
                Vehiculo vehiculo = config.leerArchivo(archivo.getAbsolutePath());


                JOptionPane.showMessageDialog(this, 
                    "Vehículo cargado:\n" +
                    "Llantas: " + vehiculo.getLlantas().getTipo() + "\n" +
                    "Motor: " + vehiculo.getMotor().getNombre());

                
                VentanaInicial nuevaVentana = new VentanaInicial(this, true, this.vehiculo); // Asegúrate que tenga ese constructor
                nuevaVentana.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "El archivo no existe.");
            }
        } catch (ArchivoExistenteException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
        }
    }
    }//GEN-LAST:event_btnConfiActionPerformed

    private void btnConfiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiMouseClicked
        
    }//GEN-LAST:event_btnConfiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCargarConfi;
    private javax.swing.JButton btnConfi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
