/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.simulador.views;

import autonoma.simulador.exception.ApagadoNoPuedeAcelerarException;
import autonoma.simulador.exception.ApagadoNoPuedeFrenarException;
import autonoma.simulador.exception.ElVeiculoPatinaException;
import autonoma.simulador.exception.SeAccidentaraException;
import autonoma.simulador.exception.YaEstaApagadoException;
import autonoma.simulador.exception.YaEstaEncendidoException;
import autonoma.simulador.models.LectorArchivoTextoPlano;
import autonoma.simulador.models.Llanta;
import autonoma.simulador.models.Motor;
import autonoma.simulador.models.Simulador;
import autonoma.simulador.models.Vehiculo;
import java.io.IOException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFrame;


/**
 *
 * @author Kamii
 */
public class VentanaJugar extends JFrame{
    private Simulador simulador;
    private Motor motor;
    /**
     * Creates new form VentanaJugar
     */
    public VentanaJugar() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        try{
            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/simulador/images/CarroFondo.png")).getImage());
        }catch(Exception e){
            System.out.println("imagen no encontrada");
        }
        leerInformacionArchivo();
    }

    
    private void leerInformacionArchivo(){
        LectorArchivoTextoPlano lector = new LectorArchivoTextoPlano();
        Motor motorVehiculo = null;
        Llanta llantasVehiculo = null;
        try{
            List<String> infoArchivo = lector.leer("config.txt");
            String[] linea1 = infoArchivo.get(0).split(" ");
            String[] linea2 = infoArchivo.get(1).split(" ");
            System.out.println(linea1[2]+linea2[1]);
            switch (linea1[2]){
                case "Buenas": llantasVehiculo = new Llanta("Buena", 110);
                case "Bonitas": llantasVehiculo = new Llanta("Bonitas", 70 );
                case "Baratas": llantasVehiculo = new Llanta("Baratas", 50 );
            }
            
            switch (linea2[1]){
                case "1000": motorVehiculo = new Motor("1000 cc", 100);
                case "2000": motorVehiculo = new Motor("2000 cc", 160);
                case "3000": motorVehiculo = new Motor("3000 cc", 220);
            }
            
            this.simulador = new Simulador(new Vehiculo(llantasVehiculo,motorVehiculo));
            this.motor = motorVehiculo;
        }catch (IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnfonfoPrincipal = new javax.swing.JLabel();
        jlbFrenar = new javax.swing.JLabel();
        jlbAcelerar = new javax.swing.JLabel();
        btnEncender = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnApagar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        velocidadActual = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnfonfoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simulador/images/fondoPrincipal.jpeg"))); // NOI18N

        jlbFrenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simulador/images/Freno.jpg"))); // NOI18N
        jlbFrenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbFrenarMouseClicked(evt);
            }
        });

        jlbAcelerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simulador/images/acelerar.jpg"))); // NOI18N
        jlbAcelerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAcelerarMouseClicked(evt);
            }
        });

        btnEncender.setBackground(new java.awt.Color(0, 0, 0));
        btnEncender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEncenderMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simulador/images/encender_40px.gif"))); // NOI18N

        javax.swing.GroupLayout btnEncenderLayout = new javax.swing.GroupLayout(btnEncender);
        btnEncender.setLayout(btnEncenderLayout);
        btnEncenderLayout.setHorizontalGroup(
            btnEncenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEncenderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        btnEncenderLayout.setVerticalGroup(
            btnEncenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEncenderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnApagar.setBackground(new java.awt.Color(0, 0, 0));
        btnApagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApagarMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simulador/images/apagar_40px.gif"))); // NOI18N

        javax.swing.GroupLayout btnApagarLayout = new javax.swing.GroupLayout(btnApagar);
        btnApagar.setLayout(btnApagarLayout);
        btnApagarLayout.setHorizontalGroup(
            btnApagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnApagarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        btnApagarLayout.setVerticalGroup(
            btnApagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnApagarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        velocidadActual.setBackground(new java.awt.Color(255, 255, 255));
        velocidadActual.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        velocidadActual.setForeground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnfonfoPrincipal)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEncender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(velocidadActual, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jlbAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnEncender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnfonfoPrincipal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(velocidadActual, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void actualiarValorActual(){
        velocidadActual.setText("Velocidad actual: " + this.motor.getVelocidadActual() + " km/h");
    }
    private void jlbAcelerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAcelerarMouseClicked
        try {
            if (!simulador.estaEncendidoElVehiculo()) {
                throw new ApagadoNoPuedeAcelerarException();
            }

            String input = JOptionPane.showInputDialog(this, "¿Cuánto desea acelerar?");
            if (input == null || input.trim().isEmpty()) {
                return;
            }

            double incremento = Double.parseDouble(input.trim());
            if (incremento <= 0) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un número mayor que cero.");
                return;
            }
            simulador.acelerarVehiculo(incremento);

            VentanaAumentarVelocidad ventana = new VentanaAumentarVelocidad();
            ventana.setVisible(true);

            this.actualiarValorActual();
            

        } catch (ApagadoNoPuedeAcelerarException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido.");
        } catch (SeAccidentaraException e) {
            VentanaAccidentar ventana = new VentanaAccidentar(this.motor);
            ventana.setVisible(true);
            JOptionPane.showMessageDialog(this, "Sobrepasó el límite permitido y se accidentó.");
            velocidadActual.setText("");
        }

    }//GEN-LAST:event_jlbAcelerarMouseClicked

    private void jlbFrenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbFrenarMouseClicked
        try {
            if (!simulador.estaEncendidoElVehiculo()) {
                throw new ApagadoNoPuedeFrenarException();
            }

            String input = JOptionPane.showInputDialog(this, "¿Cuánto desea frenar?");
            if (input == null || input.trim().isEmpty()) {
                return;
            }

            double decremento = Double.parseDouble(input.trim());

            if (decremento <= 0) {
                JOptionPane.showMessageDialog(this, "Ingrese un valor mayor a 0.");
                return;
            }

            
            try {
                simulador.frenarBruscamenteVehiculo(decremento);
            } catch (ElVeiculoPatinaException e) {
                VentanaPatinar ventana = new VentanaPatinar();
                ventana.setVisible(true);
                this.simulador.recuperarControlVehiuclo();
                this.actualiarValorActual();
            }

            this.actualiarValorActual();

        } catch (ApagadoNoPuedeFrenarException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido.");
        } catch (ElVeiculoPatinaException e) { 
            VentanaPatinar ventana = new VentanaPatinar();
            ventana.setVisible(true);
            JOptionPane.showMessageDialog(this, e.getMessage());
            this.simulador.recuperarControlVehiuclo();
            this.actualiarValorActual();
        }
    }//GEN-LAST:event_jlbFrenarMouseClicked

    private void btnApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApagarMouseClicked
        try{
            this.simulador.apagarVehiculo();
            velocidadActual.setText("");
        }catch(YaEstaApagadoException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }catch(SeAccidentaraException e){
            JOptionPane.showMessageDialog(this, "se apago en una velocidad superios a 60km/h y se accidento");
            velocidadActual.setText("");
        }
        
    }//GEN-LAST:event_btnApagarMouseClicked

    private void btnEncenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncenderMouseClicked

    try {
        this.simulador.encenderVehiculo();
        this.actualiarValorActual();
        VentanaEncender ventana = new VentanaEncender();
        ventana.setVisible(true);
    } catch (YaEstaEncendidoException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
        

    }//GEN-LAST:event_btnEncenderMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnApagar;
    private javax.swing.JPanel btnEncender;
    private javax.swing.JLabel btnfonfoPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbAcelerar;
    private javax.swing.JLabel jlbFrenar;
    private javax.swing.JLabel velocidadActual;
    // End of variables declaration//GEN-END:variables
}
