/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package autonoma.simulador.views;

import autonoma.simulador.models.Vehiculo;
import autonoma.simulador.sounds.ReproductorSonido;
import javax.swing.ImageIcon;
import javax.swing.JDialog;

/**
* @author Maria Camila Prada
*@version 1.0.0
* @since 2025-04-06
*/
public class VentanaPatinar extends javax.swing.JDialog {

    /**
     * Creates new form VentanaPatinar
     */
    public VentanaPatinar(JDialog parent, boolean modal ) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        ReproductorSonido.reproducir("sonidoLlantasPatinan.wav");
        try{
            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/simulador/images/CarroFondo.png")).getImage());
        }catch(Exception e){
            System.out.println("imagen no encontrada");
        }
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbPatinar = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlbPatinar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simulador/gifs/carroPatina.gif"))); // NOI18N
        jlbPatinar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbPatinarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbPatinar)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbPatinar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbPatinarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbPatinarMouseClicked
        ReproductorSonido.detener();
        this.dispose();
    }//GEN-LAST:event_jlbPatinarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlbPatinar;
    // End of variables declaration//GEN-END:variables
}
